apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis

spec:
  # type: NodePort
  ports:
    # the port that this service should serve on
  - protocol: TCP
    name: redis
    port: 6379
    # targetPort: 6379
    # nodePort: 30001
  - protocol: TCP
    name: http
    port: 80
  #externalIPs:
  #  - 192.168.64.3
  selector:
    app: redis
